-- CREATE TABLE WYF_KLIENCI (
--     id_klienta NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
--     imie VARCHAR2(50) NOT NULL,
--     nazwisko VARCHAR2(50) NOT NULL,
--     email VARCHAR2(100) NOT NULL UNIQUE,
--     telefon VARCHAR2(15) DEFAULT NULL
-- );


-- -- Tabela: Pracownicy
-- CREATE TABLE WYF_PRACOWNICY (
--     id_pracownika NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
--     imie VARCHAR2(50) NOT NULL,
--     nazwisko VARCHAR2(50) NOT NULL,
--     stanowisko VARCHAR2(50) NOT NULL,
--     wynagrodzenie NUMBER(10, 2) CONSTRAINT CHK_WYNAGRODZENIE CHECK (wynagrodzenie >= 0)
-- );

-- -- Tabela: Filmy
-- CREATE TABLE WYF_FILMY (
--     id_filmu NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
--     tytul VARCHAR2(100) NOT NULL,
--     gatunek VARCHAR2(50) NOT NULL,
--     rok_produkcji NUMBER(4) CONSTRAINT CHK_ROK_PRODUKCJI CHECK (rok_produkcji BETWEEN 1900 AND 2100),
--     ilosc_kopii NUMBER CONSTRAINT CHK_ILOSC_KOPII CHECK (ilosc_kopii >= 0)
-- );
-- ALTER TABLE WYF_FILMY
-- ADD rezyser VARCHAR2(100) DEFAULT 'Nieznany' NOT NULL;

-- Procedura zmniejszajaca liczbe ilosc_kopii w tabeli filmy po wypożyczeniu filmu
-- CREATE OR REPLACE TRIGGER decrease_copies_after_rental
-- AFTER INSERT ON WYF_WYPOŻYCZENIA
-- FOR EACH ROW
-- BEGIN
--   -- Zmniejszenie liczby kopii filmu o 1 po każdym wypożyczeniu
--   UPDATE WYF_FILMY
--   SET ilosc_kopii = ilosc_kopii - 1
--   WHERE id_filmu = :NEW.id_filmu
--     AND ilosc_kopii > 0;  -- Zapewnia, że liczba kopii nie stanie się ujemna
-- END;
-- /


-- CREATE TABLE WYF_WYPOŻYCZENIA (
--     id_wypozyczenia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Unikalny identyfikator wypożyczenia
--     data_wypozyczenia DATE NOT NULL, -- Data wypożyczenia
--     data_zwrotu DATE DEFAULT NULL, -- Data zwrotu (opcjonalna)
--     id_klienta NUMBER NOT NULL, -- Identyfikator klienta (z tabeli WYF_KLIENCI)
--     id_filmu NUMBER NOT NULL, -- Identyfikator filmu (z tabeli WYF_FILMY)
--     koszt NUMBER(10, 2) DEFAULT 0, -- Koszt wypożyczenia (opcjonalnie z domyślną wartością 0)
--     CONSTRAINT FK_WYPOZYCZENIA_KLIENCI FOREIGN KEY (id_klienta) REFERENCES WYF_KLIENCI(id_klienta), -- Klucz obcy do tabeli WYF_KLIENCI
--     CONSTRAINT FK_WYPOZYCZENIA_FILMY FOREIGN KEY (id_filmu) REFERENCES WYF_FILMY(id_filmu) -- Klucz obcy do tabeli WYF_FILMY
-- );

--Procedura dodawania do tabeli opłaty po wypożyczeniu filmu
-- CREATE OR REPLACE TRIGGER TRG_AFTER_INSERT_WYPOZYCZENIA
-- AFTER INSERT ON WYF_WYPOŻYCZENIA
-- FOR EACH ROW
-- BEGIN
--     INSERT INTO WYF_OPLATY (kwota, data_oplaty, id_klienta, id_wypozyczenia)
--     VALUES (:NEW.koszt, :NEW.data_wypozyczenia, :NEW.id_klienta, :NEW.id_wypozyczenia);
-- END;
-- /

-- CREATE TABLE WYF_OPLATY (
--     id_oplaty NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Unikalny identyfikator opłaty
--     kwota NUMBER(10, 2) NOT NULL CONSTRAINT CHK_KWOTA CHECK (kwota > 0),  -- Kwota opłaty (musi być większa od 0)
--     data_oplaty DATE NOT NULL,  -- Data uiszczenia opłaty
--     id_klienta NUMBER NOT NULL,  -- Identyfikator klienta (z tabeli WYF_KLIENCI)
--     id_wypozyczenia NUMBER NOT NULL,  -- Identyfikator wypożyczenia (z tabeli WYF_WYPOŻYCZENIA)
    
--     -- Klucz obcy do tabeli WYF_KLIENCI
--     CONSTRAINT FK_OPLATY_KLIENCI FOREIGN KEY (id_klienta) REFERENCES WYF_KLIENCI(id_klienta),
    
--     -- Klucz obcy do tabeli WYF_WYPOŻYCZENIA
--     CONSTRAINT FK_OPLATY_WYPOZYCZENIA FOREIGN KEY (id_wypozyczenia) REFERENCES WYF_WYPOŻYCZENIA(id_wypozyczenia)
-- );

-- -- Tabela: Promocje
-- CREATE TABLE WYF_PROMOCJE (
--     id_promocji NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
--     nazwa_promocji VARCHAR2(100) NOT NULL,
--     rabat NUMBER(5, 2) NOT NULL CONSTRAINT CHK_RABAT CHECK (rabat BETWEEN 0 AND 100),
--     data_start DATE NOT NULL,
--     data_koniec DATE NOT NULL
-- );


-- -- Tabela: Klienci-Promocje (relacja wiele-do-wielu) - z 5 kolumnami
-- CREATE TABLE WYF_KLIENCI_PROMOCJE (
--     id_klienta NUMBER NOT NULL,
--     id_promocji NUMBER NOT NULL,
--     data_przypisania DATE DEFAULT SYSDATE,
--     status VARCHAR2(20) DEFAULT 'aktywna' NOT NULL,
--     uwagi VARCHAR2(255) DEFAULT NULL,
--     PRIMARY KEY (id_klienta, id_promocji),
--     CONSTRAINT FK_KLIENCI_PROMOCJE_KLIENCI FOREIGN KEY (id_klienta) REFERENCES WYF_KLIENCI(id_klienta),
--     CONSTRAINT FK_KLIENCI_PROMOCJE_PROMOCJE FOREIGN KEY (id_promocji) REFERENCES WYF_PROMOCJE(id_promocji)
-- );

--FILMY 
--INSERT INTO WYF_FILMY (tytul, gatunek, rok_produkcji, ilosc_kopii) VALUES ('Inception', 'Science Fiction', 2010, 5);
--INSERT INTO WYF_FILMY (tytul, gatunek, rok_produkcji, ilosc_kopii, rezyser) VALUES ('The Godfather', 'Crime', 1972, 3, 'Francis Ford Coppola')
--INSERT INTO WYF_FILMY (tytul, gatunek, rok_produkcji, ilosc_kopii, rezyser) VALUES ('Interstellar', 'Science Fiction', 2014, 10,'Christopher Nolan');
--INSERT INTO WYF_FILMY (tytul, gatunek, rok_produkcji, ilosc_kopii, rezyser) VALUES('Dark Knight', 'Action', 2008, 20,'Christopher Nolan');
--INSERT INTO WYF_FILMY (tytul, gatunek, rok_produkcji, ilosc_kopii, rezyser) VALUES('Forrest Gump', 'Drama', 1994, 25,'Robert Zemeckis');
--INSERT INTO WYF_FILMY (tytul, gatunek, rok_produkcji, ilosc_kopii, rezyser) VALUES ('Seven', 'Drama', 1995, 7,'David Fincher');
--INSERT INTO WYF_FILMY (tytul, gatunek, rok_produkcji, ilosc_kopii, rezyser) VALUES ('Whiplash', 'Psychological Drama', 2014, 13,'Damien Chazelle');
--INSERT INTO WYF_FILMY (tytul, gatunek, rok_produkcji, ilosc_kopii, rezyser) VALUES ('The Intouchables', 'Comedy/Drama', 2011, 16,'Olivier Nakache');
--INSERT INTO WYF_FILMY (tytul, gatunek, rok_produkcji, ilosc_kopii, rezyser) VALUES ('The Intouchables', 'Action', 2012, 10,'Joss Whedon');
--INSERT INTO WYF_FILMY (tytul, gatunek, rok_produkcji, ilosc_kopii, rezyser) VALUES ('Prisoners', 'Thriller', 2013, 9,'Denis Villeneuve');

--KLIENCI
--INSERT INTO WYF_KLIENCI (imie, nazwisko, email, telefon) VALUES ('Anna', 'Kowalska', 'anna.kowalska41@gmail.com', '553123142');
--INSERT INTO WYF_KLIENCI (imie, nazwisko, email, telefon) VALUES ('Jan', 'Nowak', 'jan.nowak12@gmail.com', '642432135');
--INSERT INTO WYF_KLIENCI (imie, nazwisko, email) VALUES ('Ewa', 'Wiśniewska', 'ewa.wisniewska22@o2.pl');
--INSERT INTO WYF_KLIENCI (imie, nazwisko, email) VALUES ('Piotr', 'Lewandowski', 'piotr.lewa231@wp.pl');
--INSERT INTO WYF_KLIENCI (imie, nazwisko, email, telefon) VALUES ('Damian', 'Bukowski', 'dab11@yachoo.com',645231645);
--INSERT INTO WYF_KLIENCI (imie, nazwisko, email, telefon) VALUES ('Andrzej', 'Michalak', 'andmich@gmail.com',864832842);
--INSERT INTO WYF_KLIENCI (imie, nazwisko, email, telefon) VALUES ('Magdalena', 'Zielińska', 'magdalena.zielinska@gmail.com', 567890123);
--INSERT INTO WYF_KLIENCI (imie, nazwisko, email, telefon) VALUES ('Barbara', 'Wójcik', 'barbara.wojcik@gmail.com',678901234);
--INSERT INTO WYF_KLIENCI (imie, nazwisko, email, telefon) VALUES ('Joanna', 'Szymańska', 'joanna.szymanska@gmail.com', 789012345);
--INSERT INTO WYF_KLIENCI (imie, nazwisko, email, telefon) VALUES ('Zbigniew', 'Bukowski', 'zbig11@yachoo.com',645231645);


--PROMOCJE
--INSERT INTO WYF_PROMOCJE (nazwa_promocji, rabat, data_start, data_koniec) VALUES ('Zniżka Świąteczna', 20.00, TO_DATE('2024-12-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'));
--INSERT INTO WYF_PROMOCJE (nazwa_promocji, rabat, data_start, data_koniec) VALUES ('Zniżka Wakacyjna', 25.00, TO_DATE('2024-7-01', 'YYYY-MM-DD'), TO_DATE('2024-8-31', 'YYYY-MM-DD'));
--INSERT INTO WYF_PROMOCJE (nazwa_promocji, rabat, data_start, data_koniec) VALUES ('Zniżka Wiosenna', 28.00, TO_DATE('2024-3-21', 'YYYY-MM-DD'), TO_DATE('2024-6-21', 'YYYY-MM-DD'));
--INSERT INTO WYF_PROMOCJE (nazwa_promocji, rabat, data_start, data_koniec) VALUES ('Zniżka Waletynki', 28.00, TO_DATE('2024-2-12', 'YYYY-MM-DD'), TO_DATE('2024-2-15', 'YYYY-MM-DD'));
--INSERT INTO WYF_PROMOCJE (nazwa_promocji, rabat, data_start, data_koniec) VALUES ('Zniżka Black Friday', 50.00, TO_DATE('2024-11-28', 'YYYY-MM-DD'), TO_DATE('2024-11-28', 'YYYY-MM-DD'));
--INSERT INTO WYF_PROMOCJE (nazwa_promocji, rabat, data_start, data_koniec) VALUES ('Zniżka 20% na 3 dni', 20, SYSDATE, SYSDATE + INTERVAL '3' DAY);
--INSERT INTO WYF_PROMOCJE (nazwa_promocji, rabat, data_start, data_koniec) VALUES ('Zniżka 10%', 10, SYSDATE, SYSDATE + INTERVAL '7' DAY);


--KLIENCI_PROMOCJE
--INSERT INTO WYF_KLIENCI_PROMOCJE (id_klienta, id_promocji, data_przypisania, status, uwagi) VALUES (1, 1, SYSDATE, 'aktywna', 'Nowy klient z rabatem 20%');
--INSERT INTO WYF_KLIENCI_PROMOCJE (id_klienta, id_promocji, data_przypisania, status, uwagi) VALUES (2, 2, SYSDATE, 'aktywna', 'Rabat 10%');
--INSERT INTO WYF_KLIENCI_PROMOCJE (id_klienta, id_promocji, data_przypisania, status, uwagi) VALUES (3, 2, SYSDATE, 'aktywna', 'Rabat 10%');
--INSERT INTO WYF_KLIENCI_PROMOCJE (id_klienta, id_promocji, data_przypisania, status, uwagi) VALUES (4, 2, SYSDATE, 'aktywna', 'Rabat 10%');
--INSERT INTO WYF_KLIENCI_PROMOCJE (id_klienta, id_promocji, data_przypisania, status, uwagi) VALUES (5, 1, SYSDATE, 'aktywna', 'Rabat 10%');
--INSERT INTO WYF_KLIENCI_PROMOCJE (id_klienta, id_promocji, data_przypisania, status, uwagi) VALUES (6, 1, SYSDATE, 'aktywna', 'Rabat 10%');
--INSERT INTO WYF_KLIENCI_PROMOCJE (id_klienta, id_promocji, data_przypisania, status, uwagi) VALUES (7, 6, SYSDATE, 'aktywna', 'Zniżka 20% na 3 dni');

--WYPOŻYCZENIA
--INSERT INTO WYF_WYPOŻYCZENIA (data_wypozyczenia, id_klienta, id_filmu,koszt) VALUES (TO_DATE('2024-12-01', 'YYYY-MM-DD'), 1, 4,15);
--INSERT INTO WYF_WYPOŻYCZENIA (data_wypozyczenia, id_klienta, id_filmu,koszt) VALUES (TO_DATE('2024-12-03', 'YYYY-MM-DD'), 2, 2,20);
--INSERT INTO WYF_WYPOŻYCZENIA (data_wypozyczenia, id_klienta, id_filmu,koszt) VALUES (TO_DATE('2024-12-01', 'YYYY-MM-DD'), 3, 4,20);
--INSERT INTO WYF_WYPOŻYCZENIA (data_wypozyczenia, id_klienta, id_filmu,koszt) VALUES (TO_DATE('2024-12-01', 'YYYY-MM-DD'), 4, 4,20);
--INSERT INTO WYF_WYPOŻYCZENIA (data_wypozyczenia, id_klienta, id_filmu,koszt) VALUES (TO_DATE('2024-12-01', 'YYYY-MM-DD'), 5, 5,20);
--INSERT INTO WYF_WYPOŻYCZENIA (data_wypozyczenia, id_klienta, id_filmu,koszt) VALUES (TO_DATE('2024-12-01', 'YYYY-MM-DD'), 6, 6,20);
--INSERT INTO WYF_WYPOŻYCZENIA (data_wypozyczenia, id_klienta, id_filmu,koszt) VALUES (TO_DATE('2024-12-01', 'YYYY-MM-DD'), 7, 7,20);
--INSERT INTO WYF_WYPOŻYCZENIA (data_wypozyczenia, id_klienta, id_filmu,koszt) VALUES (TO_DATE('2024-12-01', 'YYYY-MM-DD'), 8,8,20);
--INSERT INTO WYF_WYPOŻYCZENIA (data_wypozyczenia, id_klienta, id_filmu,koszt) VALUES (TO_DATE('2024-12-01', 'YYYY-MM-DD'), 9, 9,20);
--INSERT INTO WYF_WYPOŻYCZENIA (data_wypozyczenia, id_klienta, id_filmu,koszt) VALUES (TO_DATE('2024-12-01', 'YYYY-MM-DD'), 10, 10,20);

--PRACOWNICY
--INSERT INTO WYF_PRACOWNICY (imie, nazwisko, stanowisko, wynagrodzenie) VALUES ('Jan', 'Kowalski', 'Kierownik', 5000.00);
--INSERT INTO WYF_PRACOWNICY (imie, nazwisko, stanowisko, wynagrodzenie) VALUES ('Anna', 'Nowak', 'Sekretarz', 3000.00);
--INSERT INTO WYF_PRACOWNICY (imie, nazwisko, stanowisko, wynagrodzenie) VALUES ('Piotr', 'Wójcik', 'Programista', 4000.00);
--INSERT INTO WYF_PRACOWNICY (imie, nazwisko, stanowisko, wynagrodzenie) VALUES ('Maria', 'Kowalczyk', 'Tester', 3500.00);
--INSERT INTO WYF_PRACOWNICY (imie, nazwisko, stanowisko, wynagrodzenie) VALUES ('Paweł', 'Zieliński', 'Administrator', 4500.00);
--INSERT INTO WYF_PRACOWNICY (imie, nazwisko, stanowisko, wynagrodzenie) VALUES ('Katarzyna', 'Woźniak', 'Manager', 5500.00);
--INSERT INTO WYF_PRACOWNICY (imie, nazwisko, stanowisko, wynagrodzenie) VALUES ('Tomasz', 'Szymański', 'Konsultant', 3800.00);
--INSERT INTO WYF_PRACOWNICY (imie, nazwisko, stanowisko, wynagrodzenie) VALUES ('Ewa', 'Lewandowska', 'Asystentka', 3200.00);
--INSERT INTO WYF_PRACOWNICY (imie, nazwisko, stanowisko, wynagrodzenie) VALUES ('Adam', 'Dąbrowski', 'Analista', 4200.00);
--INSERT INTO WYF_PRACOWNICY (imie, nazwisko, stanowisko, wynagrodzenie) VALUES ('Agnieszka', 'Kwiatkowska', 'Specjalista IT', 4700.00);